### ISSUE TITLE
max-len (한줄에 허용하는 character 수)

### ISSUE THREAD

**Issue by ildukim** [Ecube-Labs/eslint-config-ecubelabs#2]
max-len 이 100 인데 너무 작은거 아닐까요?
제가 글자를 크게 해서 보는데도 130 정도는 한 화면에 들어오는데 말입니다

**Comment by parkmeta** [comment]
저도 그렇게 생각합니다. 더 늘리는 게 문제가 되지 않는다면 120정도로 하는 게 어떨까요?

**Comment by ildukim** [comment]
@dolsup @selenehyun 
관심 좀 주세요

**Comment by selenehyun** [comment]
앗 지송함미다
늦게봤네요. max-len은 사실 저에게 의미가 없지만 남들이 그렇게 쓰길래 해둔거라서... 에어비엔비는 80으로 한다던데...
일단 전 160까지도 ok임다.

**Comment by ildukim** [comment]
의견 감사합니다
