### ISSUE TITLE
CA-345 lint 룰 논의

### ISSUE THREAD

**Issue by dolsup** [Ecube-Labs/eslint-config-ecubelabs#4]
# [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline)
`minProperties: _number_` 옵션을 쓰면 좋을 것 같습니다.
잘 바뀌지 않을 적은 수의 프로퍼티를 나열할 때도 개행을 하는 건 불편한 것 같습니다.
자율로 맡기는 것도 좋을 것 같습니다.

# [quotes](https://eslint.org/docs/rules/quotes)
`avoidEscape: true` 옵션을 쓰면 좋을 것 같습니다.
현재는 escaping을 위해 backtick 을 쓰는 경우에도 실패합니다.

# [dot-notation](https://eslint.org/docs/rules/dot-notation)
이건 좋은데.. 
![2018-10-30 4 48 38](https://user-images.githubusercontent.com/8360934/47703457-b157e280-dc63-11e8-9224-11c0e9d81adc.png)
이렇게 스페이스가 들어가서 dot notation을 쓸 수 없는 프로퍼티가 있을 때 일관성을 위해 전부 저렇게 쓴 예가 있는데 어떻게 하는게 좋을까요? 저기서는 그냥 object spreading을 해버릴 수도 있긴 한데.. dot notation을 우선하는 건 너무 당연하기 때문에 자율로 맡기는 것도 좋다고 생각합니다. 애초에 status에 스페이스가 안 들어갔다면 참 좋았겠지만요..

**Comment by ildukim** [comment]
@selenehyun @parkmeta 의견 주세요

**Comment by selenehyun** [comment]
object-curly-newline은 4~6개의 프로퍼티를 넘으면 무조건 개행하도록 강제하면 좋겠네요.
----
quotes 는 동의하지만 어쨌든 기본 설정은 single로 가는거죠?
----
전 dot notation은 무조건 지키면 좋겠습니다. 저는 저거랑 비슷한 예로 아래처럼 하고있는데, key를 string으로 넣어야 하는 상황에서 필요한 프로퍼티만 사용하는것처럼 했으면 좋겠습니다.
![image](https://user-images.githubusercontent.com/10769487/47704956-8b810c80-dc68-11e8-9c8d-230bb92a6687.png)

**Comment by parkmeta** [comment]
저도 dot notation은 필요하다고 생각합니다. 예외적인 경우는 allowPattern에 추가하는 게 좋을 것 같아요.

**Comment by dolsup** [comment]
object-curly-newline은 어차피 길어지면 max-len에 걸리니까 자율로 하는 건 어떨까요? 프로퍼티가 자주 바뀔지, 프로퍼티 이름의 길이가 어떨지는 코드마다 다르니까요.
dot-notation은 그대로 가도 좋습니다.

**Comment by dolsup** [comment]
참고로 지금 CA에서 lint에 걸리는 룰은 저 셋과 max-len밖에 없습니다. 🎉

**Comment by parkmeta** [comment]
max-len이 120이라 한 줄에 많으면 10개 이상도 올 수 있지 않을까요? 어느 정도 제한은 있는 게 좋지 않을까 합니다.

**Comment by selenehyun** [comment]
프로퍼티 이름의 길이가 긴것들이 많은 경우에는 6개도 매우 보기 힘들어집니다.
고로 전 적당한 타협을 봤다고 생각하는 6개를 하는게 어떨까 싶습니다.

**Comment by selenehyun** [comment]
만약 object-curly-newline과 max-len이 서로 연관성이 있어서 minProperty가 6이어도 120을 넘으면 알아서 줄을 잘라준다면 말이 달라지겠지만요

**Comment by ildukim** [comment]
@dolsup @selenehyun @parkmeta 
- object-curly-newline. minProperty = 6
- quotes.avoidEscape = true
- dot-notation 그대로
가 결론인가요?

**Comment by parkmeta** [comment]
@dolsup 과 같이 일관성을 지켜야 하는 경우에는 그 부분에만 comment로 예외를 두는 게 좋다고 생각합니다. 저런 상황은 어쩔 수 없다고 해도 권장되지는 않으니까요. 고로 전 @ildukim 결론에 동의합니다.

**Comment by dolsup** [comment]
땅땅땅
