### ISSUE TITLE
Rules conflict

### ISSUE THREAD

**Issue by ildukm** [Ecube-Labs/eslint-config-ecubelabs#7]
- https://eslint.org/docs/2.13.1/rules/no-mixed-operators
- https://eslint.org/docs/rules/no-extra-parens

1 + 2 * 3 // no-mixed-operators 위반 --- (1)
1 + (2 * 3) // no-extra-parens 룰 때문에 prettier 가 parens 제거 함 --- (2)

conflict 을 해결하기 위해서는 (1), (2) 중 어떤 컨벤션을 사용할지 결정해야 합니다.

**Comment by dolsup** [comment]
저는 (1)에 한표입니다.
예시로 드신 케이스는 누구나 이해 가능하지만 복잡한 상황에서는 연산자 우선순위를 모두가 정확히 알 수도 없고 괄호를 명시적으로 써주는 게 코드 파악에 도움이 된다고 생각합니다.

**Comment by dolsup** [comment]
아 헷갈리네요 저는 no-mixed-operators + yes-extra-parens 파입니다

**Comment by parkmeta** [comment]
저도 명시적으로 괄호가 필요하다고 생각합니다. json 의견과 같습니다.

**Comment by ghojeong** [comment]
저도 no-mixed-operators + yes-extra-parens 쪽이 오해의 소지가 적을 것 같아 좋다고 생각합니다.

**Comment by selenehyun** [comment]
저는 이미 2처럼 사용하는곳이 많습니다.
제가 잘 헷갈리기 때문에...

**Comment by punkywhite** [comment]
연산자 우선 순위에 의해 아무리 무의미한 괄호라 할지라도 명시적으로 해놓는게 좋지요
